### ISSUE TITLE
질문드립니다.

### ISSUE THREAD

**Issue by ckswls56** [HyungJoonSon/CED-Front#1]
retrofit을 라이브러리로 사용하는 이유가 무엇인가요?

**Comment by HyungJoonSon** [comment]
retrofit은 HTTP API를 별도 조작 없이 쉽게 응답을 객체로 변환해주는 라이브러리입니다. 코틀린을 사용한다면 API 호출 시 내부적으로 요청이 이루어져서 따로 콜백을 정의할 필요없이 응답객체를 받을 수 있습니다.
